### ISSUE TITLE
palm detection 

### ISSUE THREAD

**Issue by AloneGu** [junhwanjang/mediapipe-models#1]
in  https://github.com/junhwanjang/mediapipe-models/blob/master/palm_detection/model.py

regressor_8 = Reshape(target_size=(-1, 18))(regressor_8) # (1, 2048, 18)
regressor_16 = Reshape(target_size=(-1, 18))(regressor_16) # (1, 512, 18)
regressor_32 = Reshape(target_size=(-1, 18))(regressor_32) # (1, 384, 18)

why last dim is 18, what's the meaning?

thx

**Comment by junhwanjang** [comment]
Hi. I checked about "last dims" just now.
I think Palm detection model generates box coordinates (4 points) and rough hand keypoints (7 points).
And hand keypoints(7 points) generated use for rotating image before running hand landmark inference.

You can check codes below.
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_detection_gpu.pbtxt#L102
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_detection_gpu.pbtxt#L173

**Comment by AloneGu** [comment]
hmm..  seems these keypoints help to locate the palms . thanks
