### ISSUE TITLE
Model architecture

### ISSUE THREAD

**Issue by metalwhale** [junhwanjang/mediapipe-models#2]
Hi @junhwanjang. Thank you so much for sharing us your interesting repo!
May I ask you some questions?
How do you know the architecture of each models? And how to generate the re-implemented models with the python script on this repo, especially the `palm_detection` without custom ops?
I have tried to read your source code but can't figure it out how to run them.
Can you please tell me more in detail? Had been searching around but still have no idea...

**Comment by junhwanjang** [comment]
- just used [Netron](https://github.com/lutzroeder/netron)

**Comment by junhwanjang** [comment]
Hi.
- Used [Netron](https://github.com/lutzroeder/netron). The app can visualize tflite model.

- I checked google mediapipe code especially on “conv2dtransposeBias”. The op could be replaced with Conv2dtranspose and Add op.

**Comment by metalwhale** [comment]
@junhwanjang, thank you for your prompt reply!
Can you also show me how to run your code? I mean I don't know which python script need to run to achieve the re-implemented model files. I just want to try generating them by myself.

**Comment by junhwanjang** [comment]
example code of generating model
```python
from model import palm_detection_model
from utils import set_pretrained_weights, convert_to_pb, convert_to_tflite

OUT_PB_PATH = "./test.pb"
OUT_TFLITE_PATH = "./test.tflite"
def main():
    # Initialized model
    model = palm_detection_model(input_size=(256, 256, 3))
    set_pretrained_weights(model)
    convert_to_pb(model, OUT_PB_PATH)
    convert_to_tflite(OUT_PB_PATH, OUT_TFLITE_PATH)
```

**Comment by metalwhale** [comment]
@junhwanjang, thank you so much!!!

**Comment by metalwhale** [comment]
@junhwanjang Can you let me ask you one more question?
Where did the [`palm_detection_weights.npy`](https://github.com/junhwanjang/mediapipe-models/blob/master/palm_detection/pretrained_weights/palm_detection_weights.npy) file come from? I tried to extract weights from [`palm_detection.tflite`](https://github.com/junhwanjang/mediapipe-models/blob/master/palm_detection/mediapipe_models/palm_detection.tflite) file by using `get_pretrained_tflite_weights` function from [`utils.py`](https://github.com/junhwanjang/mediapipe-models/blob/master/hand_landmark/utils.py) but encountered custom op error.
AFAIK we can't read `tflite` file with Python API but the `.npy` extension of pretrained weights file which indicated that file was created by some Python script. This made me confused.

**Comment by junhwanjang** [comment]
Yes it's right. "palm_detection_weights.npy" file extracted in another custom-build-tensorflow environment.

The previous "palm_detection.tflite" file can load only in custom-build-environment(including with Mediapipe custom op)

**Comment by metalwhale** [comment]
Got it! Thank you so much again, @junhwanjang!!
