### ISSUE TITLE
How to create without custom op version of tflite file?

### ISSUE THREAD

**Issue by joel1895** [junhwanjang/mediapipe-models#3]
Hi,

I am trying to use mediapipe's hair segmentation model in script but I am coming across the error of 

`RuntimeError:`` Encountered unresolved custom op: MaxPoolingWithArgmax2D.Node number 12 (MaxPoolingWithArgmax2D) failed to prepare.`

can you please explain how did you created the without custom op version of the mediapipe model?

**Comment by junhwanjang** [comment]
Google-mediapipe has supported now the custom ops in any playform via their library. You don't need to convert it w/o.
