### ISSUE TITLE
Full hand tracking pipeline

### ISSUE THREAD

**Issue by wolterlw** [junhwanjang/mediapipe-models#4]
Hello @junhwanjang 
I was wandering if you would be interested in incorporating your tensorflow models into [this repo](https://github.com/wolterlw/hand_tracking). As of now I use mediapipe's tflite models which prevents me from running on a desktop GPU and introduces build difficulties.
If you would be interested in collaborating I would be happy to help out.

**Comment by junhwanjang** [comment]
Hi @wolterlw 
Yes sure. you can use my converted tensorflow models.
Just be sure to cite my repo.
It would be pleased to help your project.
Thanks.
