### ISSUE TITLE
use .pb  model with tensorflow-gpu in Desktop?

### ISSUE THREAD

**Issue by lilyswang** [junhwanjang/mediapipe-models#5]
Hi , @junhwanjang 。Thanks for your nice job. I want to know how to use the .pb  model in  tensorflow-gpu,  I try  it but get some error like " can't  load the .pb  "   or 'not such file '  

Can you give me some suggestions or some exmaples?  Thanks a lot.

**Comment by lilyswang** [comment]
OSError: SavedModel file does not exist at: ./pb_model/palm/{saved_model.pbtxt|saved_model.pb}

**Comment by junhwanjang** [comment]
python```
def load_inference_graph(model_path):
    # load frozen tensorflow model into memory
    print("> ====== loading HAND frozen graph into memory")
    graph = tf.Graph()
    with graph.as_default():
        od_graph_def = tf.GraphDef()
        with tf.gfile.GFile(model_path, 'rb') as fid:
            serialized_graph = fid.read()
            od_graph_def.ParseFromString(serialized_graph)
            tf.import_graph_def(od_graph_def, name='')
        sess = tf.Session(graph=detection_graph)
    print(">  ====== Hand Inference graph loaded.")
    return graph, sess
```
did you try it?

**Comment by lilyswang** [comment]
Sorry for my  late reply !  Thank for your suggestions ,it works now.   I used it with a wrong method  before.
